#! /bin/sh -e
# This file is automatically generated with: tup generate build.sh
export tup_vardict="$(cd $(dirname $0) && pwd)/tup-generate.vardict"
(gcc -Wall -O2 -c hello.c -o hello.o)
(gcc hello.o -o hello)
